### ISSUE TITLE
LastAccessedDate

### ISSUE THREAD

**Issue by christianhaller3000** [philipbarwi/secretservice#1]
Ich glaube, LastAccessedDate wird beim Auslesen der Secrets leider verändert. So lässt sich nach dem ersten Ausführen des secretservice (cooler Name btw) nicht mehr sagen, ob es wirklich nie benutzt wird.

**Comment by vo55** [comment]
Hey,
es gibt zwei Regeln - einmal "not rotated" und einmal "unused". 
Hierfür normalisiere ich zwei verschiedene Felder in ['LastUsed'] bzw. ['LastRotated'].

Beim Secretsmanager werden diese so gesetzt:
'LastRotated': secret['LastChangedDate'],
'LastUsed': secret['LastAccessedDate'],

Das LastAccessedDate das letztmalige auslesen wiederspiegelt passt also und wird nur für die Regel "unused secrets" verwendet.
