### ISSUE TITLE
ich habe keine Ahnung von Python

### ISSUE THREAD

**Issue by christianhaller3000** [philipbarwi/secretservice#2]
...aber ich musste `python3 -m pip install pytz ` noch installieren, damit es ging

**Comment by vo55** [comment]
Danke dir - der wurde in den requirements vergessen.

**Comment by vo55** [comment]
Fixed with https://github.com/philipbarwi/secretservice/commit/6c23a72aed7077a02a62d7da5fc8c2e2330de83c
