### ISSUE TITLE
AWS Region

### ISSUE THREAD

**Issue by christianhaller3000** [philipbarwi/secretservice#3]
Ich musste eine Region reinreichen, damit es lief:
`AWS_DEFAULT_REGION=eu-central-1 ./secrets-cli -p assets-infrastructure-developer`

Besser wäre es vermutlich noch, wenn über alle Regionen gerannt wird.

**Comment by vo55** [comment]
So i looked into this and there is a different handling depending on the service necessary:
SSM (SecureStrings) - iterate through regions
IAM AccessKeys - not regional
Secretsmanager - iterate through regions

**Comment by vo55** [comment]
Fixed with https://github.com/philipbarwi/secretservice/pull/4
